# Generated by Django 2.2.24 on 2023-09-17 18:16

from django.db import migrations


def is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year < 2015:
            flat.new_building = False
        else:
            flat.new_building = True
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20230917_1921'),
    ]

    operations = [
        migrations.RunPython(is_new_building),
    ]
