# Generated by Django 2.2.24 on 2023-09-20 14:38

from django.db import migrations
import phonenumbers


def copy_renewed_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        flat_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(flat_phonenumber):
            formatted_phonenumber = phonenumbers.format_number(flat_phonenumber, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = formatted_phonenumber
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230920_1435'),
    ]

    operations = [
        migrations.RunPython(copy_renewed_phones),
    ]