# Generated by Django 2.2.24 on 2023-09-21 18:35

from django.db import migrations


def add_connection_with_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(
            owner=owner.full_name,
            owners_phonenumber=owner.owner_phonenumber)
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230921_2135'),
    ]

    operations = [
        migrations.RunPython(add_connection_with_flat)
    ]
