# Generated by Django 2.2.24 on 2023-09-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20230924_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phonenumber',
        ),
    ]
